# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.31.5-standalone/all.json

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
        - name: app
          image: logoutput
          imagePullPolicy: Never
